name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Publicar
        uses: actions/deploy-pages@v2
