name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: './src'

      - name: Deploy
        uses: actions/deploy-pages@v2